import assert from 'node:assert/strict';
import test from 'node:test';
import {parseShoppingIntent,rankShoppingProducts} from '../lib/shopping-intent.ts';
import type {ProductResult} from '../lib/types.ts';
const prompts=['telefons līdz 600 € ar labu kameru','gaming laptop līdz 1200 € ar vismaz 16GB RAM','55 collu OLED TV ar 120Hz','salīdzini iPhone 16 un Samsung Galaxy S25','portatīvais darbam un video montāžai līdz 1500 €'];
test('all five requested AI intents preserve budgets, specs and separate comparison targets',()=>{
 const p=prompts.map(parseShoppingIntent);assert.equal(p[0].maxPrice,600);assert.equal(p[0].category,'smartphone');assert.equal(p[1].maxPrice,1200);assert.equal(p[1].requiredSpecs.ram,'16 GB');assert.equal(p[1].requiredSpecs.storage,undefined);assert.equal(p[2].requiredSpecs.size,'55');assert.equal(p[2].requiredSpecs.refreshRate,'120 Hz');assert.equal(p[2].requiredSpecs.panelType,'OLED');assert.deepEqual(p[3].comparisonTargets,['iPhone 16','Samsung Galaxy S25']);assert.equal(p[4].category,'laptop');assert.equal(p[4].maxPrice,1500);
});
function product():ProductResult{return {id:'p',externalId:'p',title:'Laptop',normalizedTitle:'laptop',bestPrice:800,currency:'EUR',dealScore:0,catalogVariants:[{id:'8',variantKey:'8',attributes:{ram:'8 GB'},offerCount:1},{id:'16',variantKey:'16',attributes:{ram:'16 GB'},offerCount:1}],offers:[{variantId:'8',merchant:'A',price:800,totalPrice:800,shipping:0,currency:'EUR',dealScore:0,isCheapest:true,isBestOverall:false},{variantId:'16',merchant:'B',price:1300,totalPrice:1300,shipping:0,currency:'EUR',dealScore:0,isCheapest:false,isBestOverall:false}]};}
test('AI never borrows cheap price from a variant that fails RAM requirements',()=>{assert.equal(rankShoppingProducts([product()],parseShoppingIntent(prompts[1])).length,0);});
test('AI recommendations link to the exact affordable matching variant',()=>{const p=product();p.offers[1].price=p.offers[1].totalPrice=1100;const rows=rankShoppingProducts([p],parseShoppingIntent(prompts[1]));assert.equal(rows[0].product.bestPrice,1100);assert.equal(rows[0].product.selectedVariantId,'16');assert.equal(rows[0].product.storesCount,1);assert.ok(rows[0].unknown.some(s=>s.includes('Spēles')));});
test('missing specs stay unknown and non-euro prices are not compared with euro budgets',()=>{const p=product();p.catalogVariants=[];p.offers=[{...p.offers[0],variantData:{},variantId:undefined}];assert.equal(rankShoppingProducts([p],parseShoppingIntent(prompts[1]))[0].matched.length,0);p.offers[0].currency='USD';assert.equal(rankShoppingProducts([p],parseShoppingIntent(prompts[1])).length,0);});
test('minimum budget is preserved',()=>{const p=parseShoppingIntent('telefons no 400 līdz 600 €');assert.equal(p.minPrice,400);assert.equal(p.maxPrice,600);});
